# Generated by Django 3.0.8 on 2020-08-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photohub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Category',
            new_name='category',
        ),
    ]
